name: Publish Docker image
on:
  release:
    types: [published]
  pull_request:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: logzio/cloudwatch-config-builder:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



